import xlsxwriter


# Create a workbook and add worksheets
workbook = xlsxwriter.Workbook('questionnaire_miel_kobo/questionnaire_miel_kobo_commercants.xlsx')
survey = workbook.add_worksheet('survey')
choices = workbook.add_worksheet('choices')
settings = workbook.add_worksheet('settings')

# Survey sheet headers
survey_headers = [
    'type', 'name', 'label', 'appearance', 'relevant', 'repeat_count'
]
survey.write_row(0, 0, survey_headers)

# Survey sheet rows (full structure)
survey_rows = [
    ['note', 'intro', '🧭 QUESTIONNAIRE COMMERÇANTS\nÉTUDE DE LA FILIÈRE MIEL EN CÔTE D’IVOIRE\nObjectif général : Collecter des données fiables et non redondantes auprès des commerçants de miel, afin d’analyser les circuits de commercialisation, la formation des prix, la qualité, les contraintes, les marges et de simuler des scénarios de chocs et de développement du marché.\nInstructions à l’enquêteur : Cocher les cases correspondantes. Renseigner précisément les champs numériques et textuels. Les sections « par période » sont à répéter si nécessaire.', '', '', ''],
    ['begin_group', 'module_a', 'MODULE A – IDENTIFICATION ET LOCALISATION', '', '', ''],
    ['text', 'enqueteur', 'Nom et prénom de l’enquêteur', '', '', ''],
    ['date', 'date_entretien', 'Date de l’entretien', '', '', ''],
    ['select_one region', 'region', 'Région', '', '', ''],
    ['text', 'departement', 'Département', '', '', ''],
    ['text', 'localite', 'Commune / Localité', '', '', ''],
    ['select_one vente_lieu', 'type_vente', 'Type de lieu de vente', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_b', 'MODULE B – PROFIL DU COMMERÇANT', '', '', ''],
    ['select_one categorie', 'categorie', 'Catégorie', '', '', ''],
    ['select_one yes_no', 'membre_org', 'Êtes-vous membre d’une organisation / association de commerçants ?', '', '', ''],
    ['text', 'nom_structure', 'Si oui, nom de la structure', '', "${membre_org}='yes'", ''],
    ['integer', 'age', 'Âge (ans)', '', '', ''],
    ['select_one sexe', 'sexe', 'Sexe', '', '', ''],
    ['text', 'nationalite', 'Nationalité', '', '', ''],
    ['text', 'telephone', 'Téléphone', '', '', ''],
    ['select_one education', 'education', 'Niveau d’éducation', '', '', ''],
    ['select_one marital', 'statut_matrimonial', 'Statut matrimonial', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_c', 'MODULE C – ACTIVITÉ COMMERCIALE DU MIEL', '', '', ''],
    ['integer', 'annee_experience', 'Années d’expérience dans le commerce du miel', '', '', ''],
    ['select_multiple appro', 'approvisionnement', 'Principales sources d’approvisionnement', '', '', ''],
    ['select_one origine', 'origine_miel', 'Origine géographique du miel', '', '', ''],
    ['select_one yes_no', 'appro_regulier', 'Approvisionnement régulier toute l’année', '', '', ''],
    ['text', 'periode_forte', 'Périodes de forte disponibilité', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_d', 'MODULE D – VOLUMES ET FLUX COMMERCIAUX', '', '', ''],
    ['integer', 'volume_achete', 'Volume moyen acheté par période (kg)', '', '', ''],
    ['integer', 'volume_vendu', 'Volume moyen vendu par période (kg)', '', '', ''],
    ['select_multiple miel', 'type_miel', 'Types de miel commercialisés', '', '', ''],
    ['select_one forme', 'forme_vente', 'Forme de vente', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_e', 'MODULE E – PRIX, COÛTS ET MARGES', '', '', ''],
    ['integer', 'prix_achat', 'Prix moyen d’achat (FCFA/kg)', '', '', ''],
    ['integer', 'prix_vente', 'Prix moyen de vente (FCFA/kg)', '', '', ''],
    ['select_multiple couts', 'couts_activite', 'Coûts liés à l’activité', '', '', ''],
    ['integer', 'marge_brute', 'Marge brute estimée (FCFA/kg)', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_f', 'MODULE F – QUALITÉ, CONSERVATION ET CONFORMITÉ', '', '', ''],
    ['select_multiple qual', 'criteres_qualite', 'Critères de qualité à l’achat', '', '', ''],
    ['select_multiple stockage', 'conditions_stockage', 'Conditions de stockage', '', '', ''],
    ['select_one contenant', 'type_contenant', 'Type de contenant', '', '', ''],
    ['select_multiple prob_qual', 'problemes_qualite', 'Problèmes de qualité rencontrés', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_g', 'MODULE G – PERTES ET RISQUES COMMERCIAUX', '', '', ''],
    ['select_one yes_no', 'pertes', 'Subissez-vous des pertes de miel ?', '', '', ''],
    ['integer', 'taux_pertes', 'Taux estimé de pertes (%)', '', "${pertes}='yes'", ''],
    ['select_multiple causes', 'causes_pertes', 'Causes des pertes', '', "${pertes}='yes'", ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_h', 'MODULE H – MARCHÉS ET CLIENTÈLE', '', '', ''],
    ['select_multiple clients', 'types_clients', 'Types de clients', '', '', ''],
    ['select_multiple marche', 'portee_marche', 'Portée du marché', '', '', ''],
    ['select_multiple prix', 'fixation_prix', 'Fixation des prix', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_i', 'MODULE I – APPUIS ET BESOINS', '', '', ''],
    ['select_multiple appui', 'appuis_recus', 'Appuis reçus', '', '', ''],
    ['select_multiple besoins', 'besoins_prioritaires', 'Besoins prioritaires', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_j', 'MODULE J – STRESS TEST ET SCÉNARIOS DE MARCHÉ', '', '', ''],
    ['integer', 'volume_annuel', 'Volume annuel vendu (kg/an)', '', '', ''],
    ['integer', 'ca_annuel', 'Chiffre d’affaires annuel estimé (FCFA)', '', '', ''],
    ['select_one amelior_qual', 'scenar_qualite', 'Amélioration de la qualité du miel', '', '', ''],
    ['select_one orga_com', 'scenar_orga', 'Meilleure organisation des commerçants', '', '', ''],
    ['select_one financement', 'scenar_financement', 'Accès au financement', '', '', ''],
    ['select_one hausse_prix', 'scenar_hausse_prix', 'Hausse des prix d’achat', '', '', ''],
    ['select_one baisse_dem', 'scenar_baisse_dem', 'Baisse de la demande', '', '', ''],
    ['select_one prob_qual_gen', 'scenar_prob_qualite', 'Problèmes de qualité généralisés', '', '', ''],
    ['select_one facteur', 'facteur_cle', 'Quel facteur aurait le plus grand impact sur votre activité ?', '', '', ''],
    ['end_group', '', '', '', '', ''],
    ['begin_group', 'module_k', 'MODULE K – OBSERVATIONS', '', '', ''],
    ['text', 'commentaires', 'Commentaires du commerçant', '', '', ''],
    ['text', 'observations', 'Observations de l’enquêteur', '', '', ''],
    ['end_group', '', '', '', '', ''],
]

for i, row in enumerate(survey_rows, 1):
    survey.write_row(i, 0, row)

choices_headers = ['list_name', 'name', 'label']
choices.write_row(0, 0, choices_headers)

choices_rows = [
    # Regions (add all as needed)
    ['region', 'abidjan', 'Abidjan'],
    ['region', 'bouake', 'Bouaké'],
    ['region', 'yamoussoukro', 'Yamoussoukro'],
    # ... (add all regions of Côte d’Ivoire)
    ['vente_lieu', 'marche', 'Marché'],
    ['vente_lieu', 'boutique', 'Boutique'],
    ['vente_lieu', 'domicile', 'Domicile'],
    ['vente_lieu', 'autre', 'Autre'],
    ['categorie', 'detail', 'Détaillant'],
    ['categorie', 'grossiste', 'Grossiste'],
    ['categorie', 'semi', 'Semi-grossiste'],
    ['categorie', 'collecteur', 'Collecteur–revendeur'],
    ['yes_no', 'yes', 'Oui'],
    ['yes_no', 'no', 'Non'],
    ['sexe', 'femme', 'Femme'],
    ['sexe', 'homme', 'Homme'],
    ['education', 'non_scol', 'Non scolarisé'],
    ['education', 'primaire', 'Primaire'],
    ['education', 'secondaire', 'Secondaire'],
    ['education', 'superieur', 'Supérieur'],
    ['marital', 'marie', 'Marié(e)'],
    ['marital', 'celibataire', 'Célibataire'],
    ['marital', 'concubinage', 'Concubinage'],
    ['appro', 'prod', 'Producteurs individuels'],
    ['appro', 'coop', 'Coopératives apicoles'],
    ['appro', 'collecteur', 'Collecteurs'],
    ['appro', 'commercant', 'Autres commerçants'],
    ['origine', 'locale', 'Locale'],
    ['origine', 'regionale', 'Régionale'],
    ['origine', 'nationale', 'Nationale'],
    ['origine', 'importee', 'Importée'],
    ['miel', 'foret', 'Forêt'],
    ['miel', 'savane', 'Savane'],
    ['miel', 'multifloral', 'Multifloral'],
    ['miel', 'autre', 'Autre'],
    ['forme', 'vrac', 'Vrac'],
    ['forme', 'conditionne', 'Conditionné'],
    ['forme', 'les_deux', 'Les deux'],
    ['couts', 'transport', 'Transport'],
    ['couts', 'stockage', 'Stockage'],
    ['couts', 'conditionnement', 'Conditionnement'],
    ['couts', 'taxes', 'Taxes / redevances'],
    ['couts', 'pertes', 'Pertes'],
    ['couts', 'autres', 'Autres'],
    ['qual', 'aspect', 'Aspect'],
    ['qual', 'gout', 'Goût'],
    ['qual', 'origine', 'Origine connue'],
    ['qual', 'confiance', 'Confiance au fournisseur'],
    ['qual', 'prix_bas', 'Prix bas'],
    ['stockage', 'sec', 'Sec'],
    ['stockage', 'abri_lumiere', 'À l’abri de la lumière'],
    ['stockage', 'hermetique', 'Récipients hermétiques'],
    ['contenant', 'plastique', 'Plastique alimentaire'],
    ['contenant', 'verre', 'Verre'],
    ['contenant', 'autre', 'Autre'],
    ['prob_qual', 'fermentation', 'Fermentation'],
    ['prob_qual', 'impuretes', 'Impuretés'],
    ['prob_qual', 'cristallisation', 'Cristallisation excessive'],
    ['prob_qual', 'adulteration', 'Adultération suspectée'],
    ['prob_qual', 'aucun', 'Aucun'],
    ['causes', 'conservation', 'Mauvaise conservation'],
    ['causes', 'chaleur', 'Chaleur excessive'],
    ['causes', 'contenant', 'Contenants inadaptés'],
    ['causes', 'mevente', 'Mévente'],
    ['causes', 'autre', 'Autre'],
    ['clients', 'menages', 'Ménages'],
    ['clients', 'revendeurs', 'Revendeurs'],
    ['clients', 'restaurateurs', 'Restaurateurs'],
    ['clients', 'pharmacies', 'Pharmacies / herboristeries'],
    ['marche', 'local', 'Local'],
    ['marche', 'regional', 'Régional'],
    ['marche', 'national', 'National'],
    ['prix', 'cout_marge', 'Coût + marge'],
    ['prix', 'marche', 'Prix du marché'],
    ['prix', 'concurrence', 'Concurrence'],
    ['prix', 'nego', 'Négociation avec clients'],
    ['appui', 'aucun', 'Aucun'],
    ['appui', 'formation', 'Formation'],
    ['appui', 'financement', 'Financement'],
    ['appui', 'organisation', 'Appui organisationnel'],
    ['besoins', 'financement', 'Accès au financement'],
    ['besoins', 'stockage', 'Stockage amélioré'],
    ['besoins', 'certification', 'Certification / contrôle qualité'],
    ['besoins', 'organisation', 'Organisation collective'],
    ['besoins', 'marche', 'Accès à de nouveaux marchés'],
    ['amelior_qual', 'plus10', '+10 %'],
    ['amelior_qual', 'plus25', '+25 %'],
    ['amelior_qual', 'plus50', '+50 %'],
    ['amelior_qual', 'plus50plus', '> +50 %'],
    ['orga_com', 'faible', 'Faible impact'],
    ['orga_com', 'moyen', 'Impact moyen'],
    ['orga_com', 'eleve', 'Impact élevé'],
    ['financement', 'volumes', 'Augmentation des volumes'],
    ['financement', 'couts', 'Réduction des coûts'],
    ['financement', 'les_deux', 'Les deux'],
    ['hausse_prix', 'moins10', '-10 %'],
    ['hausse_prix', 'moins25', '-25 %'],
    ['hausse_prix', 'moins50', '-50 %'],
    ['hausse_prix', 'moins50plus', '> -50 %'],
    ['baisse_dem', 'moins10', '-10 %'],
    ['baisse_dem', 'moins25', '-25 %'],
    ['baisse_dem', 'moins50', '-50 %'],
    ['baisse_dem', 'moins50plus', '> -50 %'],
    ['prob_qual_gen', 'faible', 'Impact faible'],
    ['prob_qual_gen', 'moyen', 'Impact moyen'],
    ['prob_qual_gen', 'eleve', 'Impact élevé'],
    ['facteur', 'qualite', 'Qualité du miel'],
    ['facteur', 'prix_achat', 'Prix d’achat'],
    ['facteur', 'organisation', 'Organisation des acteurs'],
    ['facteur', 'financement', 'Accès au financement'],
    ['facteur', 'demande', 'Demande des consommateurs'],
]

for i, row in enumerate(choices_rows, 1):
    choices.write_row(i, 0, row)

workbook.close()

# Add settings sheet
settings_headers = ['form_title', 'form_id', 'version', 'default_language']
settings.write_row(0, 0, settings_headers)
settings_row = [
    '🧭 QUESTIONNAIRE COMMERÇANTS - FILIÈRE MIEL CI',
    'questionnaire_miel_kobo_commercants',
    '2026-01-09',
    'fr'
]
settings.write_row(1, 0, settings_row)

print("XLSForm created: questionnaire_miel_kobo_commercants.xlsx in questionnaire_miel_kobo/ (with settings sheet)")
